import "./panel";
import { initDirectionalActions } from "./directionalActions";
import { initCheckAnatomy } from "./checkAnatomy";
import { initInquiryPaths } from "./inquiryPaths";
import { initInquiryTrace } from "./inquiryTrace";
import { initResearcherProfiles } from "./researcherProfiles";
import { initResearcherTeaching } from "./researcherTeaching";
import { initHistoryControls } from "./historyControls";
import { initWikipediaHarvestPanel } from "./wikipediaHarvest";
import { initWikipediaFrontierCapturePanel } from "./wikipediaFrontierCapture";
import { initOperatorSnapshotCapture } from "./operatorSnapshotCapture";

initDirectionalActions();
initCheckAnatomy();
initInquiryPaths();
initInquiryTrace();
initResearcherProfiles();
initResearcherTeaching();
void initHistoryControls();
void initWikipediaHarvestPanel();
void initWikipediaFrontierCapturePanel();
initOperatorSnapshotCapture();
